{
 "title": "Tiltify Analytics",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "event", "query": { "query": "label_values(donation,event)" } }
  ]
 },
 "panels": [
  { "title": "Event Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Amount Raised",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(event) (donation{event=~\"$event\"})",
     "legendFormat": "Donation Total"
    }
   ]
  },
  {
   "title": "Total Amount without Incentives applied",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event) (sum_over_time(donation{event=~\"$event\", poll=\"\", reward=\"0\", target=\"\"}[$__range]))",
     "legendFormat": "Donation Total"
    }
   ]
  },
  {
   "title": "Donations Totals Per day",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(event) (sum_over_time(donation{event=~\"$event\"}[1d]))",
     "legendFormat": "Donation Total"
    },
    {
     "expr": "count by(event) (count_over_time(donation{event=~\"$event\"}[1d]))",
     "legendFormat": "Donation Count Total"
    }
   ]
  },
  {
   "title": "# of Donations Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(event) (donation{event=~\"$event\"})",
     "legendFormat": "Donation Total"
    }
   ]
  },
  {
   "title": "# of Donations without Incentives applied",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event) (count_over_time(donation{event=~\"$event\", poll=\"\", reward=\"0\", target=\"\"}[$__range]))",
     "legendFormat": "Donation Total"
    }
   ]
  },
  {
   "title": "Incentive categories",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event) (sum_over_time(donation{event=~\"$event\", poll!=\"\"}[7d]))",
     "legendFormat": "Polls"
    },
    {
     "expr": "sum by(event) (sum_over_time(donation{event=~\"$event\", reward!=\"0\"}[7d]))",
     "legendFormat": "Rewards"
    },
    {
     "expr": "sum by(event) (sum_over_time(donation{event=~\"$event\", target!=\"\"}[7d]))",
     "legendFormat": "Targets"
    }
   ]
  },
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Donations over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "count by(event) (donation{event=~\"$event\"})",
     "legendFormat": "Donation Count Total"
    },
    {
     "expr": "sum by(event) (donation{event=~\"$event\"})",
     "legendFormat": "Donation Total"
    }
   ]
  },
  {
   "title": "# of Donations Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event) (count_over_time(donation{event=~\"$event\"}[7d]))",
     "legendFormat": "Donation Total"
    }
   ]
  },
  {
   "title": "# of Donations without Incentives applied",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event) (count_over_time(donation{event=~\"$event\", poll=\"\", reward=\"0\", target=\"\"}[7d]))",
     "legendFormat": "Donation Total"
    }
   ]
  },
  {
   "title": "Total Amount Raised",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(event) (sum_over_time(donation{event=~\"$event\"}[$__range]))",
     "legendFormat": "Donation Total"
    }
   ]
  },
  {
   "title": "Total Amount without Incentives applied",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event) (sum_over_time(donation{event=~\"$event\", poll=\"\", reward=\"0\", target=\"\"}[7d]))",
     "legendFormat": "Donation Total"
    }
   ]
  },
  { "title": "Incentive Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Incentive categories",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event) (sum_over_time(donation{event=~\"$event\", poll!=\"\"}[$__range]))",
     "legendFormat": "Polls"
    },
    {
     "expr": "sum by(event) (sum_over_time(donation{event=~\"$event\", reward!=\"0\"}[$__range]))",
     "legendFormat": "Rewards"
    },
    {
     "expr": "sum by(event) (sum_over_time(donation{event=~\"$event\", target!=\"\"}[$__range]))",
     "legendFormat": "Targets"
    }
   ]
  },
  {
   "title": "Target",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(target) (sum_over_time(donation{event=~\"$event\", target!=\"\"}[$__range]))",
     "legendFormat": "{{poll}}"
    }
   ]
  },
  {
   "title": "Polls",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(poll) (sum_over_time(donation{event=~\"$event\", poll!=\"\"}[$__range]))",
     "legendFormat": "{{poll}}"
    }
   ]
  },
  {
   "title": "Forecasting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Donation Forecast",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "predict_linear(sum by(event) (donation{event=~\"$event\"})[1h],4*3600)",
       "legendFormat": "Prediction"
      },
      {
       "expr": "sum by(event) (donation{event=~\"$event\"})",
       "legendFormat": "Dontaion Total"
      }
     ]
    }
   ]
  }
 ]
}