{
 "title": "Tiltify Analytics Copy",
 "time": { "from": "2025-06-28T10:00:00.000Z", "to": "2025-07-05T21:59:59.000Z" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "campaign",
    "query": {
     "query": "label_values(donation{team=~\"$team\"},campaign)"
    }
   },
   { "name": "team", "query": { "query": "label_values(donation,team)" } }
  ]
 },
 "panels": [
  { "title": "Team Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Amount Raised",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(donation{}[30d]))",
     "legendFormat": "Donation Total {{campaign}}"
    }
   ]
  },
  {
   "title": "Total Amount without Incentives applied",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(team) (sum_over_time(donation{team=~\"$team\", poll=\"\", reward=\"0\", target=\"\"}[90d]))",
     "legendFormat": "Donation Total {{team}}"
    }
   ]
  },
  {
   "title": "Donations over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(team) (count_over_time(donation{team=~\"$team\"}[30d]))",
     "legendFormat": "Donation Count Total {{campaign}}"
    },
    {
     "expr": "sum by(team) (sum_over_time(donation{team=~\"$team\"}[30d]))",
     "legendFormat": "Donation Total  {{campaign}}"
    }
   ]
  },
  {
   "title": "# of Donations Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(team) (count_over_time(donation{team=~\"$team\"}[90d]))",
     "legendFormat": "{{campaign}}"
    }
   ]
  },
  {
   "title": "# of Donations without Incentives applied",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(team) (count_over_time(donation{team=~\"$team\", poll=\"\", reward=\"0\", target=\"\"}[90d]))",
     "legendFormat": "{{campaign}}"
    }
   ]
  },
  {
   "title": "Donations Totals Per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(team) (sum_over_time(donation{team=~\"$team\"})[1d])",
     "legendFormat": "Donation Total {{campaign}}"
    },
    {
     "expr": "sum by(team) (count_over_time(donation{team=~\"$team\"}[1d]))",
     "legendFormat": "Donation Count"
    }
   ]
  },
  {
   "title": "Incentive categories",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(team) (sum_over_time(donation{ poll!=\"\"}[7d]))",
     "legendFormat": "Polls"
    },
    {
     "expr": "sum by(yeam) (sum_over_time(donation{team=~\"$team\", reward!=\"0\"}[7d]))",
     "legendFormat": "Rewards"
    },
    {
     "expr": "sum by(team) (sum_over_time(donation{team=~\"$team\", target!=\"\"}[7d]))",
     "legendFormat": "Targets"
    }
   ]
  },
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Donations over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(campaign) (count_over_time(donation{campaign=~\"$campaign\"}[30d]))",
     "legendFormat": "Donation Count Total {{campaign}}"
    },
    {
     "expr": "sum by(campaign) (sum_over_time(donation{campaign=~\"$campaign\"}[30d]))",
     "legendFormat": "Donation Total  {{campaign}}"
    }
   ]
  },
  {
   "title": "Donations Totals Per day",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum by(campaign) (sum_over_time(donation{campaign=~\"$campaign\"})[1d])",
     "legendFormat": "Donation Total {{campaign}}"
    },
    {
     "expr": "sum by(campaign) (count_over_time(donation{campaign=~\"$campaign\"}[1d]))",
     "legendFormat": "Donation Count {{campaign}}"
    }
   ]
  },
  {
   "title": "# of Donations Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(campaign) (count_over_time(donation{campaign=~\"$campaign\"}[$__range]))",
     "legendFormat": "{{campaign}}"
    }
   ]
  },
  {
   "title": "# of Donations without Incentives applied",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(campaign) (count_over_time(donation{campaign=~\"$campaign\", poll=\"\", reward=\"0\", target=\"\"}[$__range]))",
     "legendFormat": "{{campaign}}"
    }
   ]
  },
  {
   "title": "Total Amount Raised",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(campaign) (sum_over_time(donation{campaign=~\"$campaign\"}[$__range]))",
     "legendFormat": "{{campaign}}"
    }
   ]
  },
  {
   "title": "Total Amount without Incentives applied",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(campaign) (sum_over_time(donation{campaign=~\"$campaign\", poll=\"\", reward=\"0\", target=\"\"}[$__range]))",
     "legendFormat": "{{campaign}}"
    }
   ]
  },
  {
   "title": "Incentive Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Target",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(target) (sum_over_time(donation{campaign=~\"$campaign\", target!=\"\"}[$__range]))",
       "legendFormat": "{{poll}}"
      }
     ]
    },
    {
     "title": "Polls",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(poll) (sum_over_time(donation{campaign=~\"$campaign\", poll!=\"\"}[$__range]))",
       "legendFormat": "{{poll}}"
      }
     ]
    }
   ]
  },
  { "title": "Forecasting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Panel Title",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "donation{team=~\"$team\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum_over_time(donation{team=~\"$team\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}